// Three static content pages (Privacy, Terms, and About/data provenance --
// see docs/ROADMAP.md Phase 6.5), bundled in one file the way auth.js
// bundles several related simple views. None of these fetch anything or
// hold state, so each render function is just a static el() tree.

import { el, mount } from "../dom.js";

function legalPage(title, ...sections) {
  return el("div", { class: "legal-page" }, el("h1", {}, title), ...sections);
}

function section(heading, ...body) {
  return el("section", { class: "card" }, el("h2", {}, heading), ...body);
}

export async function renderPrivacyView(container) {
  mount(
    container,
    legalPage(
      "Privacy policy",
      el("p", { class: "hint" }, "Last updated 2026-08-10."),
      section(
        "What this site is",
        el(
          "p",
          {},
          "Research Finder helps students find academic research labs by field, location, and institution. The " +
            "professor, institution, and publication data on this site is drawn from public sources -- see "
        ),
        el(
          "p",
          {},
          el("a", { href: "#/about" }, "About & data provenance"),
          " for details on exactly where each field comes from."
        )
      ),
      section(
        "What we store if you create an account",
        el("p", {}, "Creating an account (Google or email/password) stores:"),
        el(
          "ul",
          {},
          el("li", {}, "Your name and email address."),
          el(
            "li",
            {},
            "A password hash (never the password itself) if you sign up with email/password, or a link to your Google " +
              "account if you use Google sign-in."
          ),
          el(
            "li",
            {},
            "A student profile, if you fill one in: education level, school, coursework, skills, prior experience, and " +
              "what you're looking for. This is used only to personalize AI summaries and cold-email drafts for you -- it is " +
              "never shown to professors or to any other user."
          ),
          el("li", {}, "Bookmarked professors and any cold-email drafts you generate or save.")
        )
      ),
      section(
        "What the AI features do with your data",
        el(
          "p",
          {},
          "Professor summaries, cold-email drafts, and resume import are generated by sending a request to an outside AI " +
            "provider (currently OpenAI). When you generate a cold-email draft, the text sent to that provider includes " +
            "your student profile along with the professor's public topics and publications. When you upload a resume to " +
            "prefill your profile, the resume text is sent the same way and is not stored beyond that request."
        ),
        el(
          "p",
          {},
          "Every AI-generated summary or draft is grounded only in data already on this site, is labeled as AI-generated " +
            "in the interface, and is editable before you do anything with it -- this app drafts, you send."
        )
      ),
      section(
        "Cookies",
        el(
          "p",
          {},
          "A single signed, HttpOnly session cookie keeps you signed in. It identifies your session only -- there is no " +
            "third-party analytics or advertising tracking on this site."
        )
      ),
      section(
        "Sharing",
        el("p", {}, "We don't sell or share account data with third parties, other than the AI provider above, as needed to generate the features you explicitly request.")
      ),
      section(
        "Corrections, removal, and questions",
        el(
          "p",
          {},
          "If you're a professor and something about your listing is wrong, use the \"Flag an issue\" button on your " +
            "profile page, or the general ",
          el("a", { href: "#/contact" }, "contact form"),
          " for anything else, including a request to remove your listing or delete your account."
        )
      )
    )
  );
}

export async function renderTermsView(container) {
  mount(
    container,
    legalPage(
      "Terms of use",
      el("p", { class: "hint" }, "Last updated 2026-08-10."),
      section(
        "What this site provides",
        el(
          "p",
          {},
          "Research Finder is an informational tool for finding academic research contacts. It does not represent any " +
            "professor or institution, and it is not affiliated with OpenAlex, ORCID, or any school listed here."
        )
      ),
      section(
        "AI-generated content",
        el(
          "p",
          {},
          "Summaries and cold-email drafts are generated by an AI model from public data and may still be inaccurate or " +
            "incomplete. Review anything generated here before you rely on it or send it to a real person."
        )
      ),
      section(
        "Your responsibility when reaching out",
        el(
          "p",
          {},
          "This app drafts a cold-email for you to review and send yourself -- it never sends anything on your behalf. " +
            "You're responsible for what you actually send and for using contact information respectfully."
        )
      ),
      section(
        "Accounts",
        el(
          "p",
          {},
          "Keep your account credentials to yourself. Don't use this site to scrape, spam, or harass anyone listed here."
        )
      ),
      section(
        "Changes",
        el("p", {}, "These terms may be updated as the site changes; material changes will update the date above.")
      )
    )
  );
}

export async function renderAboutView(container) {
  mount(
    container,
    legalPage(
      "About & data provenance",
      section(
        "Where the data comes from",
        el(
          "p",
          {},
          "Institution, professor, publication, and research-topic data is sourced from ",
          el("a", { href: "https://openalex.org/", target: "_blank", rel: "noopener" }, "OpenAlex"),
          ", a free, public catalog of scholarly works and authors. Professors are matched to institutions using " +
            "OpenAlex's own \"who currently works here\" records, not inferred from co-authorship on shared papers -- an " +
            "earlier approach that produced attribution mistakes and was rebuilt for this reason."
        )
      ),
      section(
        "ORCID enrichment",
        el(
          "p",
          {},
          "For professors with an ORCID iD, we cross-check that ORCID record's own employment history to catch " +
            "wrong-person matches, and pull in a personal website and public, ORCID-verified email if one is listed. " +
            "Nothing is scraped or guessed -- a missing website, email, or research topic means it isn't on the source " +
            "record, not that we didn't look."
        )
      ),
      section(
        "Institution classification",
        el(
          "p",
          {},
          "Institution type (e.g. \"Research University\") comes from ACE/Indiana University's real Carnegie " +
            "Classification data, not a heuristic guess."
        )
      ),
      section(
        "AI-generated content",
        el(
          "p",
          {},
          "Professor summaries and cold-email drafts are generated by an AI model, strictly grounded in the topics and " +
            "publications already shown on this site, and are always labeled as AI-generated. See the ",
          el("a", { href: "#/privacy" }, "privacy policy"),
          " for what's sent to the AI provider."
        )
      ),
      section(
        "Something wrong or want to be removed?",
        el(
          "p",
          {},
          "Every professor page has a \"Flag an issue\" button for reporting a specific problem (wrong person, outdated " +
            "contact info, and so on). For anything else -- including removing a listing entirely -- use the ",
          el("a", { href: "#/contact" }, "contact form"),
          "."
        )
      )
    )
  );
}
